### ISSUE TITLE
TP: Fix promiseless error workaround [URGENT]

### ISSUE THREAD

**Issue by therobinkim** [hyperledger/education-cryptomoji#100]
https://github.com/hyperledger/education-cryptomoji/commit/4fc3fcfed18cd244dba8218bafdb35d136b37b31 is causing:

1. `Maximum call stack size exceeded` errors:

```
rest - api | [2018 - 06 - 28 02: 17: 22.953 INFO     helpers] POST / batches HTTP / 1.1: 202 status, 352 size, in 0.012682 s
client | 172.18.0.1 - -[28 / Jun / 2018: 02: 17: 22 + 0000] "POST /api/batches HTTP/1.1" 202 188
processor | Unhandled error on sendBack RangeError: Maximum call stack size exceeded
processor | at new Promise(<anonymous>)
processor      |     at MojiHandler.handler.apply (/processor/index.js:21:12)
processor      |     at MojiHandler.handler.apply (/processor/index.js:19:20)
processor      |     at MojiHandler.handler.apply (/processor/index.js:19:20)
processor      |     at MojiHandler.handler.apply (/processor/index.js:19:20)
processor      |     at MojiHandler.handler.apply (/processor/index.js:19:20)
processor      |     at MojiHandler.handler.apply (/processor/index.js:19:20)
processor      |     at MojiHandler.handler.apply (/processor/index.js:19:20)
processor      |     at MojiHandler.handler.apply (/processor/index.js:19:20)
processor      |     at MojiHandler.handler.apply (/processor/index.js:19:20)
```

2. `502` errors 60 seconds after a new request comes in (only for changing state; reading state works just fine):

```
rest - api | [2018 - 06 - 28 02: 25: 19.252 INFO     helpers] POST / batches HTTP / 1.1: 202 status, 352 size, in 0.006664 s
client | 172.18.0.1 - -[28 / Jun / 2018: 02: 25: 19 + 0000] "POST /api/batches HTTP/1.1" 202 188
client | [Thu Jun 28 02: 26: 19.331171 2018][proxy_http: error][pid 90: tid 140594957485824](70007)The timeout specified has expired: [client 172.18.0.1: 57170] AH01102: error reading status line from remote server rest - api: 8008, referer: http://localhost:3000/moji/5f4d7601f0220ea895a1dae41406e1400e49aef234d9f1d5c0aab4bd68066687300184
client | [Thu Jun 28 02: 26: 19.331230 2018][proxy: error][pid 90: tid 140594957485824][client 172.18.0.1: 57170]AH00898: Error reading from remote server returned by / api / batch_statuses, referer: http://localhost:3000/moji/5f4d7601f0220ea895a1dae41406e1400e49aef234d9f1d5c0aab4bd68066687300184
client | 172.18.0.1 - -[28 / Jun / 2018: 02: 25: 19 + 0000] "GET /api/batch_statuses?id=4a55475008eb6822f5a0263b165221d5f27a7a2ef7000330bf25567ce3b40867210372ac633d993073937e7aca391931da751cc842fb3818698531dd3ec8bff1&wait HTTP/1.1" 502 415
```

Reverting this commit eliminates these errors, but as discussed in Slack:
> it is pretty important that [the promiseless error workaround] works
> otherwise any students throwing naked errors will kill their TP

We'll need to come up with a fix and deploy ASAP as this is part of the prompt code on the `master` branch.

**Comment by therobinkim** [comment]
Closed by #101
